//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerMatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Sessions
    {
        public int Game_Session_ID { get; set; }
        public Nullable<System.DateTime> Session_Start { get; set; }
        public Nullable<System.DateTime> Session_End { get; set; }
        public Nullable<int> Game_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
