//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerMatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public Rating()
        {
            this.User_ID = 0;
            this.Behavior_Score = 0;
        }
    
        public int User_Rating_ID { get; set; }
        public Nullable<int> User_Rating { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Game_ID { get; set; }
        public Nullable<int> Behavior_Score { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
