//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerMatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session_Users
    {
        public int Id { get; set; }
        public int Game_Session_ID { get; set; }
        public int Users_ID { get; set; }
    
        public virtual Game_Sessions Game_Sessions { get; set; }
        public virtual User User { get; set; }
    }
}
